name: Commit Hello World and Tweet
on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Write Hello World in commits
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check the pixel for today
        uses: ./ # Uses an action in the root directory
        id: todaysPixel
      # Use the output from `todaysPixel`
      - name: Make a commit
        if: steps.todaysPixel.outputs.commit == 'true'
        run: |
          ./incrementCommitCounter.sh
          git config user.name "hello-world-action"
          git config user.email ${{ secrets.USER_EMAIL }}
          git add numberOfDays.txt
          git commit -m "Github Actions Commit"
          git push
      - name: setup
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: install
        run: npm install 
      - name: Take screenshot and manipulate
        run: | 
          node screenshot.js 
          node compositeImage.js
      - name: Tweet It 
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY  }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: node tweet.js

